/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scary.glb -T -S
Author: shedmon (https://sketchfab.com/shedmon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/scary-creature-b996bf84da3d49edb52202cb4fab457c
Title: Scary Creature
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Scary(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/scary-transformed.glb");
  const { actions } = useAnimations(animations, group);

  console.log(actions);

  useEffect(() => {
    actions["Idle"].play();
  }, []);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={20}
      position={[0, -72, -22]}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="622514e609dd4561994df6a714ad8ccbfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.thing}
                    skeleton={nodes.Object_7.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scary-transformed.glb");
