/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 toilet.glb --transform --simplify --keepnames --shadows
Author: Kevin Johnson / Sushi Burgerrr (https://sketchfab.com/Pittree)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toilet-868beb5a0e6840d7a1d647a42a5e5a8c
Title: Toilet
*/

import { useGLTF } from "@react-three/drei";

export default function Toilet(props) {
  const { nodes, materials } = useGLTF("/toilet-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group
        name="toilet"
        position={[-1.08, -2.313, 0]}
        scale={0.03}
        rotation={[0, -Math.PI / 2, 0]}
      >
        <group name="group2" position={[-0.55, -6.35, 4.98]} scale={1.12}>
          <mesh
            name="sandaran"
            castShadow
            receiveShadow
            geometry={nodes.pCube21_lambert2_0.geometry}
            material={materials.lambert2}
          />
          <mesh
            name="tutup atas"
            castShadow
            receiveShadow
            geometry={nodes.pCube22_lambert2_0.geometry}
            material={materials.lambert2}
          />
        </group>
        <group
          name="group3"
          position={[11.76, 0.94, 3.22]}
          scale={[1, 0.86, 1]}
        >
          <mesh
            name="kaki bawah"
            castShadow
            receiveShadow
            geometry={nodes.pCylinder2_lambert2_0.geometry}
            material={materials.lambert2}
          />
          <mesh
            name="lid"
            castShadow
            receiveShadow
            geometry={nodes.pCylinder3_lambert2_0.geometry}
            material={materials.lambert2}
          />
        </group>
        <mesh
          name="pCube23_lambert2_0"
          castShadow
          receiveShadow
          geometry={nodes.pCube23_lambert2_0.geometry}
          material={materials.lambert2}
        />
        <mesh
          name="pCylinder4_lambert1_0"
          castShadow
          receiveShadow
          geometry={nodes.pCylinder4_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          name="pCylinder5_lambert2_0"
          castShadow
          receiveShadow
          geometry={nodes.pCylinder5_lambert2_0.geometry}
          material={materials.lambert2}
          position={[0.6, 0, 0]}
        />
        <mesh
          name="pCube24_lambert2_0"
          castShadow
          receiveShadow
          geometry={nodes.pCube24_lambert2_0.geometry}
          material={materials.lambert2}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/toilet-transformed.glb");
